# Copyright (C) 2023 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

#create_clock -name sys_clk_0_0_clk_p -period 5.000 [get_ports sys_clk_0_0_clk_p]

###############################################################################
#
#     channel 0
#
###############################################################################
# IO standards

#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {sys_clk_0_0_clk_n[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {sys_clk_0_0_clk_p[0]}]


#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ck_c_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ck_c_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ck_t_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ck_t_b[0]}]

#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_c_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_c_a[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_c_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_c_b[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_t_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_t_a[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_t_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dqs_t_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_a[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_ca_b[5]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cke_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cke_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cke_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cke_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cs_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cs_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cs_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_cs_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dmi_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dmi_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dmi_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dmi_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[10]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[11]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[12]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[13]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[14]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[15]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[6]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[7]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[8]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_a[9]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[10]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[11]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[12]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[13]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[14]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[15]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[6]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[7]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[8]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_dq_b[9]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH0_LPDDR4_0_0_reset_n[0]}]
#set_property DRIVE 8 [get_ports {CH0_LPDDR4_0_0_reset_n[0]}]

# Pin placement

set_property PACKAGE_PIN N24 [get_ports {sys_clk_0_0_clk_n[0]}]
set_property PACKAGE_PIN N23 [get_ports {sys_clk_0_0_clk_p[0]}]


set_property PACKAGE_PIN M28 [get_ports {CH0_LPDDR4_0_0_ck_c_a[0]}]
set_property PACKAGE_PIN N27 [get_ports {CH0_LPDDR4_0_0_ck_c_b[0]}]
set_property PACKAGE_PIN N28 [get_ports {CH0_LPDDR4_0_0_ck_t_a[0]}]
set_property PACKAGE_PIN P26 [get_ports {CH0_LPDDR4_0_0_ck_t_b[0]}]

set_property PACKAGE_PIN AF28 [get_ports {CH0_LPDDR4_0_0_dqs_c_a[0]}]
set_property PACKAGE_PIN M23 [get_ports {CH0_LPDDR4_0_0_dqs_c_a[1]}]
set_property PACKAGE_PIN Y27 [get_ports {CH0_LPDDR4_0_0_dqs_c_b[0]}]
set_property PACKAGE_PIN U22 [get_ports {CH0_LPDDR4_0_0_dqs_c_b[1]}]
set_property PACKAGE_PIN AE28 [get_ports {CH0_LPDDR4_0_0_dqs_t_a[0]}]
set_property PACKAGE_PIN M22 [get_ports {CH0_LPDDR4_0_0_dqs_t_a[1]}]
set_property PACKAGE_PIN Y28 [get_ports {CH0_LPDDR4_0_0_dqs_t_b[0]}]
set_property PACKAGE_PIN V21 [get_ports {CH0_LPDDR4_0_0_dqs_t_b[1]}]

set_property PACKAGE_PIN T28 [get_ports {CH0_LPDDR4_0_0_ca_a[0]}]
set_property PACKAGE_PIN R27 [get_ports {CH0_LPDDR4_0_0_ca_a[1]}]
set_property PACKAGE_PIN U27 [get_ports {CH0_LPDDR4_0_0_ca_a[2]}]
set_property PACKAGE_PIN R28 [get_ports {CH0_LPDDR4_0_0_ca_a[3]}]
set_property PACKAGE_PIN M27 [get_ports {CH0_LPDDR4_0_0_ca_a[4]}]
set_property PACKAGE_PIN L28 [get_ports {CH0_LPDDR4_0_0_ca_a[5]}]
set_property PACKAGE_PIN T25 [get_ports {CH0_LPDDR4_0_0_ca_b[0]}]
set_property PACKAGE_PIN K26 [get_ports {CH0_LPDDR4_0_0_ca_b[1]}]
set_property PACKAGE_PIN R26 [get_ports {CH0_LPDDR4_0_0_ca_b[2]}]
set_property PACKAGE_PIN P25 [get_ports {CH0_LPDDR4_0_0_ca_b[3]}]
set_property PACKAGE_PIN L26 [get_ports {CH0_LPDDR4_0_0_ca_b[4]}]
set_property PACKAGE_PIN M26 [get_ports {CH0_LPDDR4_0_0_ca_b[5]}]

set_property PACKAGE_PIN K27 [get_ports {CH0_LPDDR4_0_0_cke_a[0]}]
set_property PACKAGE_PIN K28 [get_ports {CH0_LPDDR4_0_0_cke_a[1]}]
set_property PACKAGE_PIN J25 [get_ports {CH0_LPDDR4_0_0_cke_b[0]}]
set_property PACKAGE_PIN T26 [get_ports {CH0_LPDDR4_0_0_cke_b[1]}]
set_property PACKAGE_PIN P27 [get_ports {CH0_LPDDR4_0_0_cs_a[0]}]
set_property PACKAGE_PIN U28 [get_ports {CH0_LPDDR4_0_0_cs_a[1]}]
set_property PACKAGE_PIN M21 [get_ports {CH0_LPDDR4_0_0_cs_b[0]}]
set_property PACKAGE_PIN T24 [get_ports {CH0_LPDDR4_0_0_cs_b[1]}]

set_property PACKAGE_PIN AC28 [get_ports {CH0_LPDDR4_0_0_dmi_a[0]}]
set_property PACKAGE_PIN U23 [get_ports {CH0_LPDDR4_0_0_dmi_a[1]}]
set_property PACKAGE_PIN V28 [get_ports {CH0_LPDDR4_0_0_dmi_b[0]}]
set_property PACKAGE_PIN N21 [get_ports {CH0_LPDDR4_0_0_dmi_b[1]}]

set_property PACKAGE_PIN AH27 [get_ports {CH0_LPDDR4_0_0_dq_a[0]}]
set_property PACKAGE_PIN AG28 [get_ports {CH0_LPDDR4_0_0_dq_a[1]}]
set_property PACKAGE_PIN AE27 [get_ports {CH0_LPDDR4_0_0_dq_a[2]}]
set_property PACKAGE_PIN AF26 [get_ports {CH0_LPDDR4_0_0_dq_a[3]}]
set_property PACKAGE_PIN AG26 [get_ports {CH0_LPDDR4_0_0_dq_a[4]}]
set_property PACKAGE_PIN AE26 [get_ports {CH0_LPDDR4_0_0_dq_a[5]}]
set_property PACKAGE_PIN AG27 [get_ports {CH0_LPDDR4_0_0_dq_a[6]}]
set_property PACKAGE_PIN AD26 [get_ports {CH0_LPDDR4_0_0_dq_a[7]}]
set_property PACKAGE_PIN L23 [get_ports {CH0_LPDDR4_0_0_dq_a[8]}]
set_property PACKAGE_PIN K24 [get_ports {CH0_LPDDR4_0_0_dq_a[9]}]
set_property PACKAGE_PIN R23 [get_ports {CH0_LPDDR4_0_0_dq_a[10]}]
set_property PACKAGE_PIN P24 [get_ports {CH0_LPDDR4_0_0_dq_a[11]}]
set_property PACKAGE_PIN T23 [get_ports {CH0_LPDDR4_0_0_dq_a[12]}]
set_property PACKAGE_PIN K23 [get_ports {CH0_LPDDR4_0_0_dq_a[13]}]
set_property PACKAGE_PIN R24 [get_ports {CH0_LPDDR4_0_0_dq_a[14]}]
set_property PACKAGE_PIN J24 [get_ports {CH0_LPDDR4_0_0_dq_a[15]}]

set_property PACKAGE_PIN AA28 [get_ports {CH0_LPDDR4_0_0_dq_b[0]}]
set_property PACKAGE_PIN Y26 [get_ports {CH0_LPDDR4_0_0_dq_b[1]}]
set_property PACKAGE_PIN AB28 [get_ports {CH0_LPDDR4_0_0_dq_b[2]}]
set_property PACKAGE_PIN W27 [get_ports {CH0_LPDDR4_0_0_dq_b[3]}]
set_property PACKAGE_PIN AA26 [get_ports {CH0_LPDDR4_0_0_dq_b[4]}]
set_property PACKAGE_PIN AB26 [get_ports {CH0_LPDDR4_0_0_dq_b[5]}]
set_property PACKAGE_PIN V25 [get_ports {CH0_LPDDR4_0_0_dq_b[6]}]
set_property PACKAGE_PIN W26 [get_ports {CH0_LPDDR4_0_0_dq_b[7]}]
set_property PACKAGE_PIN L22 [get_ports {CH0_LPDDR4_0_0_dq_b[8]}]
set_property PACKAGE_PIN K21 [get_ports {CH0_LPDDR4_0_0_dq_b[9]}]
set_property PACKAGE_PIN J21 [get_ports {CH0_LPDDR4_0_0_dq_b[10]}]
set_property PACKAGE_PIN R21 [get_ports {CH0_LPDDR4_0_0_dq_b[11]}]
set_property PACKAGE_PIN R22 [get_ports {CH0_LPDDR4_0_0_dq_b[12]}]
set_property PACKAGE_PIN T21 [get_ports {CH0_LPDDR4_0_0_dq_b[13]}]
set_property PACKAGE_PIN P22 [get_ports {CH0_LPDDR4_0_0_dq_b[14]}]
set_property PACKAGE_PIN J22 [get_ports {CH0_LPDDR4_0_0_dq_b[15]}]

set_property PACKAGE_PIN L24 [get_ports {CH0_LPDDR4_0_0_reset_n[0]}]


#########################################################################
#
#     channel 1
#
###############################################################################
# IO standards

#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ck_c_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ck_c_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ck_t_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ck_t_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_c_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_c_a[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_c_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_c_b[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_t_a[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_t_a[1]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_t_b[0]}]
#set_property IOSTANDARD DIFF_LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dqs_t_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_a[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_ca_b[5]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cke_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cke_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cke_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cke_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cs_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cs_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cs_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_cs_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dmi_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dmi_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dmi_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dmi_b[1]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[10]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[11]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[12]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[13]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[14]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[15]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[6]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[7]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[8]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_a[9]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[0]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[10]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[11]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[12]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[13]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[14]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[15]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[1]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[2]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[3]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[4]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[5]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[6]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[7]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[8]}]
#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_dq_b[9]}]

#set_property IOSTANDARD LVSTL_11 [get_ports {CH1_LPDDR4_0_0_reset_n[0]}]
#set_property DRIVE 8 [get_ports {CH1_LPDDR4_0_0_reset_n[0]}]

# Pin placement

set_property PACKAGE_PIN AB17 [get_ports {CH1_LPDDR4_0_0_ck_c_a[0]}]
set_property PACKAGE_PIN AG16 [get_ports {CH1_LPDDR4_0_0_ck_c_b[0]}]
set_property PACKAGE_PIN AB18 [get_ports {CH1_LPDDR4_0_0_ck_t_a[0]}]
set_property PACKAGE_PIN AG17 [get_ports {CH1_LPDDR4_0_0_ck_t_b[0]}]

set_property PACKAGE_PIN AD11 [get_ports {CH1_LPDDR4_0_0_dqs_c_a[0]}]
set_property PACKAGE_PIN AE23 [get_ports {CH1_LPDDR4_0_0_dqs_c_a[1]}]
set_property PACKAGE_PIN AH19 [get_ports {CH1_LPDDR4_0_0_dqs_c_b[0]}]
set_property PACKAGE_PIN AA23 [get_ports {CH1_LPDDR4_0_0_dqs_c_b[1]}]
set_property PACKAGE_PIN AD12 [get_ports {CH1_LPDDR4_0_0_dqs_t_a[0]}]
set_property PACKAGE_PIN AD24 [get_ports {CH1_LPDDR4_0_0_dqs_t_a[1]}]
set_property PACKAGE_PIN AG20 [get_ports {CH1_LPDDR4_0_0_dqs_t_b[0]}]
set_property PACKAGE_PIN Y24 [get_ports {CH1_LPDDR4_0_0_dqs_t_b[1]}]

set_property PACKAGE_PIN AC13 [get_ports {CH1_LPDDR4_0_0_ca_a[0]}]
set_property PACKAGE_PIN AB14 [get_ports {CH1_LPDDR4_0_0_ca_a[1]}]
set_property PACKAGE_PIN AC16 [get_ports {CH1_LPDDR4_0_0_ca_a[2]}]
set_property PACKAGE_PIN AB15 [get_ports {CH1_LPDDR4_0_0_ca_a[3]}]
set_property PACKAGE_PIN AB20 [get_ports {CH1_LPDDR4_0_0_ca_a[4]}]
set_property PACKAGE_PIN AC20 [get_ports {CH1_LPDDR4_0_0_ca_a[5]}]
set_property PACKAGE_PIN AE19 [get_ports {CH1_LPDDR4_0_0_ca_b[0]}]
set_property PACKAGE_PIN AF19 [get_ports {CH1_LPDDR4_0_0_ca_b[1]}]
set_property PACKAGE_PIN AG15 [get_ports {CH1_LPDDR4_0_0_ca_b[2]}]
set_property PACKAGE_PIN AG18 [get_ports {CH1_LPDDR4_0_0_ca_b[3]}]
set_property PACKAGE_PIN AF18 [get_ports {CH1_LPDDR4_0_0_ca_b[4]}]
set_property PACKAGE_PIN AF14 [get_ports {CH1_LPDDR4_0_0_ca_b[5]}]

set_property PACKAGE_PIN AB21 [get_ports {CH1_LPDDR4_0_0_cke_a[0]}]
set_property PACKAGE_PIN AC11 [get_ports {CH1_LPDDR4_0_0_cke_a[1]}]
set_property PACKAGE_PIN AG11 [get_ports {CH1_LPDDR4_0_0_cke_b[0]}]
set_property PACKAGE_PIN AG12 [get_ports {CH1_LPDDR4_0_0_cke_b[1]}]

set_property PACKAGE_PIN AB12 [get_ports {CH1_LPDDR4_0_0_cs_a[0]}]
set_property PACKAGE_PIN AC22 [get_ports {CH1_LPDDR4_0_0_cs_a[1]}]
set_property PACKAGE_PIN AD19 [get_ports {CH1_LPDDR4_0_0_cs_b[0]}]
set_property PACKAGE_PIN AH12 [get_ports {CH1_LPDDR4_0_0_cs_b[1]}]

set_property PACKAGE_PIN AC19 [get_ports {CH1_LPDDR4_0_0_dmi_a[0]}]
set_property PACKAGE_PIN AF24 [get_ports {CH1_LPDDR4_0_0_dmi_a[1]}]
set_property PACKAGE_PIN AH13 [get_ports {CH1_LPDDR4_0_0_dmi_b[0]}]
set_property PACKAGE_PIN V22 [get_ports {CH1_LPDDR4_0_0_dmi_b[1]}]

set_property PACKAGE_PIN AC14 [get_ports {CH1_LPDDR4_0_0_dq_a[0]}]
set_property PACKAGE_PIN AD14 [get_ports {CH1_LPDDR4_0_0_dq_a[1]}]
set_property PACKAGE_PIN AD22 [get_ports {CH1_LPDDR4_0_0_dq_a[2]}]
set_property PACKAGE_PIN AE22 [get_ports {CH1_LPDDR4_0_0_dq_a[3]}]
set_property PACKAGE_PIN AD20 [get_ports {CH1_LPDDR4_0_0_dq_a[4]}]
set_property PACKAGE_PIN AD21 [get_ports {CH1_LPDDR4_0_0_dq_a[5]}]
set_property PACKAGE_PIN AC17 [get_ports {CH1_LPDDR4_0_0_dq_a[6]}]
set_property PACKAGE_PIN AD17 [get_ports {CH1_LPDDR4_0_0_dq_a[7]}]
set_property PACKAGE_PIN AH24 [get_ports {CH1_LPDDR4_0_0_dq_a[8]}]
set_property PACKAGE_PIN AD25 [get_ports {CH1_LPDDR4_0_0_dq_a[9]}]
set_property PACKAGE_PIN AE24 [get_ports {CH1_LPDDR4_0_0_dq_a[10]}]
set_property PACKAGE_PIN AH25 [get_ports {CH1_LPDDR4_0_0_dq_a[11]}]
set_property PACKAGE_PIN AG23 [get_ports {CH1_LPDDR4_0_0_dq_a[12]}]
set_property PACKAGE_PIN AH23 [get_ports {CH1_LPDDR4_0_0_dq_a[13]}]
set_property PACKAGE_PIN AG25 [get_ports {CH1_LPDDR4_0_0_dq_a[14]}]
set_property PACKAGE_PIN AF25 [get_ports {CH1_LPDDR4_0_0_dq_a[15]}]

set_property PACKAGE_PIN AG22 [get_ports {CH1_LPDDR4_0_0_dq_b[0]}]
set_property PACKAGE_PIN AH14 [get_ports {CH1_LPDDR4_0_0_dq_b[1]}]
set_property PACKAGE_PIN AH17 [get_ports {CH1_LPDDR4_0_0_dq_b[2]}]
set_property PACKAGE_PIN AH20 [get_ports {CH1_LPDDR4_0_0_dq_b[3]}]
set_property PACKAGE_PIN AG21 [get_ports {CH1_LPDDR4_0_0_dq_b[4]}]
set_property PACKAGE_PIN AH18 [get_ports {CH1_LPDDR4_0_0_dq_b[5]}]
set_property PACKAGE_PIN AH15 [get_ports {CH1_LPDDR4_0_0_dq_b[6]}]
set_property PACKAGE_PIN AH22 [get_ports {CH1_LPDDR4_0_0_dq_b[7]}]
set_property PACKAGE_PIN AA22 [get_ports {CH1_LPDDR4_0_0_dq_b[8]}]
set_property PACKAGE_PIN Y23 [get_ports {CH1_LPDDR4_0_0_dq_b[9]}]
set_property PACKAGE_PIN Y22 [get_ports {CH1_LPDDR4_0_0_dq_b[10]}]
set_property PACKAGE_PIN V23 [get_ports {CH1_LPDDR4_0_0_dq_b[11]}]
set_property PACKAGE_PIN W24 [get_ports {CH1_LPDDR4_0_0_dq_b[12]}]
set_property PACKAGE_PIN AA21 [get_ports {CH1_LPDDR4_0_0_dq_b[13]}]
set_property PACKAGE_PIN V24 [get_ports {CH1_LPDDR4_0_0_dq_b[14]}]
set_property PACKAGE_PIN W25 [get_ports {CH1_LPDDR4_0_0_dq_b[15]}]

set_property PACKAGE_PIN L25 [get_ports {CH1_LPDDR4_0_0_reset_n[0]}]
